### ISSUE TITLE
generated classes cannot be used with the :main directive if they have a - in the namespace

### ISSUE THREAD

**Issue by bmabey** [technomancy/leiningen#30]
I have reproduced this here:

https://gist.github.com/338153/44403dc808add9b2c9fb94296a7bc29e9a0ad8a2

You can clone it with:
git clone git://gist.github.com/338153.git gist-338153

This used to work with Leiningen 1.0.1 but does not with Leiningen 1.1.0.

I have tried using "foo-bar.core" in the project.clj as well.  It compiles but then when I run the jar it blows up saying "Exception in thread "main" java.lang.NoClassDefFoundError: foo-bar/core".
