### ISSUE TITLE
lein compile fails with a java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by michalmarczyk** [technomancy/leiningen#266]
Since [69bdaa3a7186b07ba8753a6d6c098cdafa9f28cd](https://github.com/technomancy/leiningen/commit/69bdaa3a7186b07ba8753a6d6c098cdafa9f28cd) (according to `git bisect`), `lein compile` fails with the following message:

``````
Exception in thread "main" java.lang.NoClassDefFoundError: 
Caused by: java.lang.ClassNotFoundException: 
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Could not find the main class: .  Program will exit.
Compilation failed.```
``````

This happens with a minimal project with a `:main` namespace specified in `project.clj`. The OS is Ubuntu 10.10; `java -version` says

```
java version "1.6.0_26"
Java(TM) SE Runtime Environment (build 1.6.0_26-b03)
Java HotSpot(TM) 64-Bit Server VM (build 20.1-b02, mixed mode)
```
