### ISSUE TITLE
Lein chokes on path with whitespaces on OS X

### ISSUE THREAD

**Issue by ubolonton** [technomancy/leiningen#143]
After upgrading to 1.4.0
    $ cd ~
    $ lein version
    Leiningen 1.4.0 on Java 1.6.0_22 Java HotSpot(TM) 64-Bit Server VM
    $ mkdir foo\ bar
    $ cd foo\ bar 
    $ lein version
    Exception in thread "main" java.lang.NoClassDefFoundError: bar
    Caused by: java.lang.ClassNotFoundException: bar
            at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
            at java.security.AccessController.doPrivileged(Native Method)
            at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
            at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
